Series 3
cleargoal/panda-monitor pull request #2
Opened 2024-09-29 13:07 UTC by cleargoal

2024-10-01 18:58 UTC, shkiper commented on app/Dto/StoreAdvertDto.php
> +            throw new InvalidArgumentException('The URL field cannot be null or empty.');
навіщо ця перевірка, в тебе і так урл не може бути null

2024-10-01 18:58 UTC, shkiper commented on app/Http/Controllers/AuthController.php
>          if (! $user || ! Hash::check($request->password, $user->password)) {
що за пробіли після !

2024-10-01 18:58 UTC, shkiper commented on app/Http/Requests/LoginRequest.php
> +            'email' => ['required', 'string', 'email'],
Це можна було б і не змінювати

2024-10-01 18:58 UTC, shkiper commented on app/Providers/AppServiceProvider.php
> +        ResetPassword::createUrlUsing(function (object $notifiable, string $token) {
а це що за конструкція і що вона тут робить?
Може її краще в AuthServiceProvider перенести?

2024-10-01 18:58 UTC, shkiper commented on app/Services/MonitorService.php
> +        if ($advert && $advert->price !== $newPrice) {
перевірку на $advert (перша), можна не робити, в тебе ж вище юзається findOrFail

2024-10-01 19:59 UTC, zhilinskiy requested changes

2024-10-01 19:59 UTC, zhilinskiy commented on app/Dto/StoreAdvertDto.php
> +    public function __construct(string $url, ?string $name = null, ?float $price = null)
Consider to use promoted properties here, see https://stitcher.io/blog/constructor-promotion-in-php-8

2024-10-01 19:59 UTC, zhilinskiy commented on app/Dto/StoreAdvertDto.php
> +class StoreAdvertDto
Consider to use readonly class here

2024-10-01 19:59 UTC, zhilinskiy commented on app/Http/Controllers/AdvertController.php
> +        $dto = $request->toDto();
Consider to inline $dto variable

2024-10-01 19:59 UTC, zhilinskiy commented on app/Http/Controllers/AuthController.php
>          return response()->json(['message' => 'User registered successfully', 'user' => $user], 201);
Consider to create [Response Macros](https://laravel.com/docs/11.x/responses#response-macros)   see https://medium.com/@JoubranJad/laravel-response-macros-for-apis-260198b3114f#:~:text=Response%20macros%20allow%20you%20to,php.

2024-10-01 19:59 UTC, zhilinskiy commented on app/Http/Requests/LoginRequest.php
> +    public function authorize(): bool
This method can be removed like in previous request

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/MonitorService.php
> +    public function __construct(ParserService $parser, NotifyService $notifier)
Consider to use promoted properties

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/MonitorService.php
>          foreach ($adverts as $advert) {
Consider to use collection methods here, so you can omit creating variable. Like Advert::get()->each(fn(Advert)=> CheckPriceChangeJob::dispatch($advert->id, $advert->url))

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/MonitorService.php
> +        InitPriceCheckingJob::dispatch(); // for starting prepare and sending notifications
Consider to fire this job in  CheckPriceChangeJob for each advert with changed price separately

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/MonitorService.php
> +        $advertData = $this->parser->getDataFromPage($sourceUrl);
Consider to return DTO from parser

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/MonitorService.php
> +        if ($advertData['price']) {
Consider to add to above DTO hasPrice() method, so you can use it inside if advertData->hasPrice()

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/MonitorService.php
>          }
Consider to fire notification job about price change here

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/MonitorService.php
> +        }])->whereDate('updated_at', today())
you can omit this complex query and data processing if you will fire notification job directly after price change

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/NotifyService.php
> +        foreach ($adverts as $advert) {
Consider to use array_map(fn($advert)=> [
                'sourceUrl' => $advert->url,
                'price' => $advert->price,
            ]) here instead of for each

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/ParserService.php
>          $content = file_get_contents($sourceUrl);
Consider to use HTTP client here, see https://laravel.com/docs/11.x/http-client. file_get_contents hard to mock inside unit tests. Also consider to return DTO from here

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/SubscribeService.php
> +    public function __construct(ParserService $parser, NotifyService $notifier)
Promoted property

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/SubscribeService.php
> +        $email = $dto->email ?? null;
Consider to add getter to DTO. Like $dto->getEmail() and return email or null from it

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/SubscribeService.php
> +        if ($user->adverts()->where('url', $dto->url)->count() === 0) {
Consider to exist() here as such query more performant

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/SubscribeService.php
> +        $advertData = $this->parser->getDataFromPage($jobData['url']);
DTO

2024-10-01 19:59 UTC, zhilinskiy commented on app/Services/SubscribeService.php
> +        if ($advertData['price']) {
hasPrice() method would be better

2024-10-01 19:59 UTC, zhilinskiy commented on routes/api.php
> +Route::post('/verification-notification', function (Request $request) {
Consider to move this code to invocable controller, see https://laravel.com/docs/11.x/controllers#single-action-controllers

2024-10-01 19:59 UTC, zhilinskiy commented on routes/auth.php
> +    ->middleware('guest')
Consider to use https://laravel.com/docs/11.x/routing#route-group-middleware here

2024-10-01 19:59 UTC, zhilinskiy commented on routes/auth.php
> +    ->middleware(['auth', 'signed', 'throttle:6,1'])
Auth routes also can be combined to https://laravel.com/docs/11.x/routing#route-group-middleware

2024-10-02 12:07 UTC, cleargoal commented on app/Dto/StoreAdvertDto.php
> +            throw new InvalidArgumentException('The URL field cannot be null or empty.');
перестраховка; та й щоб повернути ексепшен.

2024-10-02 12:12 UTC, cleargoal commented on app/Http/Controllers/AuthController.php
>          if (! $user || ! Hash::check($request->password, $user->password)) {
Зкопіпастив з пакету breeze здається і не помітив.
Зараз виправив.
Дякую!

2024-10-02 12:15 UTC, cleargoal commented on app/Http/Requests/LoginRequest.php
> +            'email' => ['required', 'string', 'email'],
Так. Не пам'ятаю навіщо це зробив. Можливо щось не працювало і шукав причини, та потім і забув про це місце.

2024-10-02 12:18 UTC, cleargoal commented on app/Providers/AppServiceProvider.php
> +        ResetPassword::createUrlUsing(function (object $notifiable, string $token) {
Я взагалі цього не робив. Мабуть встановилося з пакетом breeze.
Я використав його для механізму підтвердження емейл.
AuthServiceProvider тут взагалі немає, то ж, мабуть, автоматом поставилося в цей.

2024-10-02 12:20 UTC, cleargoal commented on app/Services/MonitorService.php
> +        if ($advert && $advert->price !== $newPrice) {
Згоден.
Виправляю

2024-10-02 12:58 UTC, cleargoal commented on app/Dto/StoreAdvertDto.php
> +    public function __construct(string $url, ?string $name = null, ?float $price = null)
Дякую!
Зрозив

2024-10-02 12:59 UTC, cleargoal commented on app/Dto/StoreAdvertDto.php
> +class StoreAdvertDto
Дійсно. Забув.
Дякую!

2024-10-02 13:03 UTC, cleargoal commented on app/Http/Controllers/AdvertController.php
> +        $dto = $request->toDto();
Done

2024-10-02 13:04 UTC, cleargoal commented on app/Http/Requests/LoginRequest.php
> +    public function authorize(): bool
I agree

2024-10-02 13:19 UTC, cleargoal commented on app/Services/MonitorService.php
> +    public function __construct(ParserService $parser, NotifyService $notifier)
I used promoted properties. After that, the Storm suggested setting them as read-only and finally making the class read-only. You can see it in the next version, but I'm not completely sure it's this way.

2024-10-02 18:29 UTC, cleargoal commented on app/Services/MonitorService.php
> +        InitPriceCheckingJob::dispatch(); // for starting prepare and sending notifications
The method started by SendPriceNotificationJob processes data to collect all users' adverts and send them to a common email. So, sending a separate email for every advert is not in business demand.

2024-10-02 18:30 UTC, cleargoal commented on app/Services/MonitorService.php
> +        $advertData = $this->parser->getDataFromPage($sourceUrl);
Do I need to create one more DTO for this purpose?

2024-10-02 18:33 UTC, cleargoal commented on app/Services/MonitorService.php
>          }
No, I described the reason above.

2024-10-02 18:33 UTC, cleargoal commented on app/Services/MonitorService.php
> +        }])->whereDate('updated_at', today())
no.

2024-10-02 18:48 UTC, cleargoal commented on app/Services/NotifyService.php
> +        foreach ($adverts as $advert) {
Thanks!
Done.

2024-10-06 16:06 UTC, merged